---
apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: system
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: kokumi
    app.kubernetes.io/managed-by: kustomize
data:
  config.yml: |
    version: 0.1
    log:
      level: info

    http:
      addr: :5000

    storage:
      filesystem:
        rootdirectory: /var/lib/registry
