---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-pvc
  namespace: system
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/component: registry
    app.kubernetes.io/part-of: kokumi
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
