---
# This file is for teaching kustomize how to substitute policyName in bindings
nameReference:
- kind: ValidatingAdmissionPolicy
  version: v1
  group: admissionregistration.k8s.io
  fieldSpecs:
  - kind: ValidatingAdmissionPolicyBinding
    version: v1
    group: admissionregistration.k8s.io
    path: spec/policyName
