---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.kokumi.dev
  resources:
  - orders
  - preparations
  - recipes
  - servings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - delivery.kokumi.dev
  resources:
  - orders/finalizers
  - preparations/finalizers
  - recipes/finalizers
  - servings/finalizers
  verbs:
  - update
- apiGroups:
  - delivery.kokumi.dev
  resources:
  - orders/status
  - preparations/status
  - recipes/status
  - servings/status
  verbs:
  - get
  - patch
  - update
