apiVersion: delivery.kokumi.dev/v1alpha1
kind: Recipe
metadata:
  labels:
    app.kubernetes.io/name: kokumi
    app.kubernetes.io/managed-by: kustomize
  name: recipe-sample
spec:
  # TODO(user): Add fields here
