## Append samples of your project ##
## Only user-creatable resources are listed here. Recipe, Preparation,
## Serving and Approval are managed by kokumi and must never be created by
## users (Approvals are submitted through the kokumi server).
namespace: kokumi

resources:
- delivery_v1alpha1_order_helm.yaml
- delivery_v1alpha1_order_kustomize.yaml
- delivery_v1alpha1_order_manifest.yaml
- delivery_v1alpha1_order_manifestfiles.yaml
- delivery_v1alpha1_order_approval.yaml
- delivery_v1alpha1_order_menu.yaml
- delivery_v1alpha1_menu.yaml
- delivery_v1alpha1_pantry_ghcr.yaml
- delivery_v1alpha1_pantry_incluster.yaml
- delivery_v1alpha1_kitchen.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
